# Create a 3x3 matrix with values ranging from 0 to 8

In [2]:
import numpy as np
matrix = np.arange(9).reshape(3,3)


In [52]:
print(f"the matrix is \n{matrix}")

the matrix is 
[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Create a random vector of size 30 and find the mean value

In [15]:
import random
np.random.seed(42)
vector = np.random.randint(0,50,(3,10))

In [18]:
vector

array([[38, 28, 14, 42,  7, 20, 38, 18, 22, 10],
       [10, 23, 35, 39, 23,  2, 21,  1, 23, 43],
       [29, 37,  1, 20, 32, 11, 21, 43, 24, 48]])

In [19]:
c = np.mean(vector)
print("the mean value for the vector is {}".format(c))

the mean value for the vector is 24.1


# Create a 10x10 array with random values and find the minimum and maximum values

In [20]:
np.random.seed(42)
arr = np.random.randint(5,50,(10,10))

In [21]:
arr

array([[43, 33, 19, 47, 12, 25, 43, 23, 27, 15],
       [15, 28, 40, 44, 28,  7, 26,  6, 28, 48],
       [34, 42,  6, 25, 37, 16, 26, 48, 29, 31],
       [46, 32, 20, 19, 48,  7, 41, 11, 25, 13],
       [43, 22,  8, 29, 18, 13, 30,  6, 24, 32],
       [11, 48, 12, 39, 18, 21, 40, 44,  8,  6],
       [10, 46,  8, 33, 22, 30, 48, 38, 14, 40],
       [18, 35, 19, 12, 18, 27, 44, 25, 20, 49],
       [22, 28, 30, 29, 49, 45, 33, 19, 49,  5],
       [29, 11, 13, 28,  5, 48, 12, 28, 15, 21]])

In [22]:
maxi = arr.max()

In [26]:
print("the maximum value is {}".format(maxi))

the maximum value is 49


In [24]:
mini = arr.min()

In [27]:
print(f"the minimum value is {mini}")

the minimum value is 5


# Create a vector with values ranging from 10 to 49

In [28]:
vector = np.arange(10,50)

In [53]:
print(f"the vector is \n{vector}")

the vector is 
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# Create a null vector of size 10 but the fifth value which is 1

In [30]:
null_vector = np.zeros(10)

In [31]:
null_vector[4] = 1

In [45]:
print(f"the null vector are {null_vector}")


the null vector are [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# Find indices of non-zero elements from [1,2,0,0,4,0]

In [41]:
ind = np.array([1,2,0,0,4,0])


In [42]:
non_zeros = ind[ind>0]

In [44]:
print(f"the non zeros are {non_zeros}")

the non zeros are [1 2 4]
